server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/portfolio/**