server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native  # Use native profile for local filesystem
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/miroRV-config