spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8089

server:
  port: 8761  # Standard port for Eureka

eureka:
  client:
    register-with-eureka: false  # Don't register itself
    fetch-registry: false        # Don't fetch registry
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false  # Optional: disable self-preservation mode
